CREATE TABLE IF NOT EXISTS posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(512) NOT NULL,
    text_ TEXT NOT NULL,
    image_path VARCHAR(512),
    tags VARCHAR(512),
    like_count BIGINT,
    comment_count BIGINT
);